# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Stretchly.Stretchly
PackageVersion: 1.18.1
PackageLocale: en-US
Publisher: Jan Hovancik
PublisherUrl: https://github.com/hovancik/stretchly
PublisherSupportUrl: https://github.com/hovancik/stretchly/issues
Author: Jan Hovancik
PackageName: Stretchly
PackageUrl: https://hovancik.net/stretchly
License: BSD-2-Clause
LicenseUrl: https://github.com/hovancik/stretchly/blob/HEAD/LICENSE
Copyright: Copyright (c) 2016-2020, Jan Hovancik
CopyrightUrl: https://github.com/hovancik/stretchly/raw/trunk/LICENSE
ShortDescription: |-
  Stretchly is a cross-platform electron app that reminds you to take breaks when working on your
  computer.
Tags:
- breaktime
- cross-platform
- reminder
ReleaseNotes: |-
  [1.18.1] - 2025-9-27
  Fixed
  - fix Linux crashes on app start
  - fix Linux issue with dbus overload
  Changed
  - updated many translations
ReleaseNotesUrl: https://github.com/hovancik/stretchly/releases/tag/v1.18.1
ManifestType: defaultLocale
ManifestVersion: 1.10.0
