# Created with YamlCreate.ps1 v2.4.4 $debug=NVS1.CRLF.7-5-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Audio_Arcade.Audio_Arcade
PackageVersion: "3.0"
DefaultLocale: fr-FR
ManifestType: version
ManifestVersion: 1.9.0


